### PR TITLE
CMS 18 updates

### PR DESCRIPTION
**Pull request by katherinetozer**
This PR
- Replaces references to the 17th edition with the 18th
- Cuts the generic pronoun line (now redundant with 5.51/5.266)
- Cuts the “acronyms should generally be spelled out…” line (now redundant with 10.3) 
- Adds the BCC title capitalization notes from our 10/30 team meeting to the Cover Copy section
- Makes the Word List more manageable:
- --Adds Word List description
- --Moves acronyms that don’t need expansion to Abbreviations/Acronyms 
- --Moves terms to avoid from Word List to the “To avoid unintentional bias” blurb
- --Cuts “Twitter user” from Word List now that it’s X and also inappropriate (I don’t feel a replacement to X user is necessary, but can add if it starts to come up). Leaves alternatives to “tweet out” and conventions.
- Consolidates footnote guidance (it just felt really clunky to me with all the divs!) and divides it into the Citation and Punctuation sections
- Adds an xref to Formatting Code in Word to the Considering Electronic Formats
- Alphabetizes many lists and subsections
- Fixes the broken Gen AI xref
- Removes bold from old changes

FYI: No changes made for casing after colons or placement of Acknowledgments. We stetted the instruction to lowercase words after colons, overruling CMS 6.67 per our 10/30 team meeting. And if we decide to move Acknowledgments to the back of the book as CMS now recommends, we could just do it and wouldn’t need to call it out in the style guide.

### CODE REVIEW

**Comment by ghyman-oreilly** [comment]
Hey Katie, should this PR get pulled into gh-pages instead of master? It currently includes a lot of commits (this happened to me too when I was updating the Word documentation).

**Comment by katherinetozer** [comment]
Hm I'll ask Theresa. Thanks for checking it out!

*Katherine Tozer *|

she/her
Senior Production Edito
r
O'Reilly Media | (617) 499-7489 | oreilly.com

**Comment by katherinetozer** [comment]
To do: in the Word List, remove Twitterstorm and update build-measure-learn cycle and ftp. Ask Tools for help adding sidebar navigation.

**Comment by kristenORM** [comment]
In Generative AI section, let's add some changes to reflect two different use cases.

- Add new paragraph at the top. "There are two main contexts where generative AI content appears: chatbot/UI interactions, and code/programming interactions. The former will appear in more non-technical books, while the latter is common in books aimed at developers and engineers. Query production if you're not sure what category something belongs in."
- Current first paragraph, change first sentence to "Display "conversational" text generated in an AI chatbot environment in blockquotes."
- Add this new content at the end of the current GenAI section. "Display content that has a programming context in a code block, with a normal paragraph separating the prompt and the response as needed. The code content should be left verbatim, for the most part, though typos can be flagged for author/production attention. There will not be syntax highlighting. Here is an example:
```
prompt = "Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened."

output = generator(prompt)

print(output[0]['generated_text'])
```

This generates the text:

```
Solution 1:

Subject: My Sincere Apologies for the Gardening Mishap

Dear Sarah,

I hope this message finds you well. I am writing to express my deep
```

**Pull request merged**
